name: Build Godot Android Plugin
description: Build Godot Android Plugin (standard or mono).
inputs:
  upload_artifact_retention_days:
    description: Retention Days to keep the Artifact
    default: 90
  godot_version:
    description: The version of Godot to be builded (3.5, 3.5.1)
    required: true
  build_version:
    description: The Build Version of Godot (stable/rc1/beta1) (`alpha` or pre-alpha` could not work).
    default: "stable"
  gradlew_build_path:
    description: The path of `.gdap` file.
    default: "./"
  project_path:
    description: The path of project.
    required: true
  godot-lib_folder_path:
    description: The path of godot-lib.
    default: "godot-lib"
    required: true
  gdap_file_path:
    description: The path of `.gdap` file.
    required: true
outputs:
  artifact_name:
    description: "Artifact name of .zip exported"
    value: ${{ steps.artifact_name_generator.outputs.artifact_name }}
runs:
  using: "composite"
  steps:
    - name: Verify current inputs godot_version
      shell: bash
      run: |
        CURRENT_GODOT_VERSION=${{ inputs.godot_version }}
        if [ ${#CURRENT_GODOT_VERSION} -eq 1 ]; then CURRENT_GODOT_VERSION="${CURRENT_GODOT_VERSION}.0"; fi
        echo "CURRENT_GODOT_VERSION=${CURRENT_GODOT_VERSION}" >> $GITHUB_ENV
    
    - id: artifact_name_generator
      name: Create Output file name variable
      shell: bash
      run: |
        OUTPUT_FILENAME=${{ github.event.repository.name }}-template-v${{env.CURRENT_GODOT_VERSION}}-${{ inputs.build_version}}
        echo "OUTPUT_FILENAME=${OUTPUT_FILENAME}" >> $GITHUB_ENV
        echo "::set-output name=artifact_name::$(echo ${OUTPUT_FILENAME})"

    - name: Download and prepare the Stable Godot .AAR LIB
      shell: bash
      run: | 
        cd ${{ inputs.godot-lib_folder_path }} 
        GODOT_AAR_LIB="godot-lib.aar"
        
        GODOT_AAR_FILENAME="godot-lib.${{env.CURRENT_GODOT_VERSION}}.${{ inputs.build_version}}"
        FULL_PATHNAME_DOWNLOAD_GODOT_AAR="https://downloads.tuxfamily.org/godotengine/${{env.CURRENT_GODOT_VERSION}}"
        
        if [ ${{ inputs.build_version}} != stable ]; then
          FULL_PATHNAME_DOWNLOAD_GODOT_AAR+=/${{ inputs.build_version}}
        fi
        
        CURRENT_GODOT_VERSION=${{env.CURRENT_GODOT_VERSION}}
        
        if [ "${CURRENT_GODOT_VERSION:0:1}" != "4" ]; then
          GODOT_AAR_FILENAME+=".release.aar"
        else
          GODOT_AAR_FILENAME+=".template_release.aar"
        fi
        
        FULL_PATHNAME_DOWNLOAD_GODOT_AAR+=/${GODOT_AAR_FILENAME}
        
        wget $FULL_PATHNAME_DOWNLOAD_GODOT_AAR
        mv $GODOT_AAR_FILENAME $GODOT_AAR_LIB
    
    - name: Grant execute permission for gradlew
      shell: bash
      run: |
        chmod +x ${{ inputs.gradlew_build_path }}gradlew
        
    - name: Build with Gradle
      shell: bash
      run: | 
        ${{ inputs.gradlew_build_path }}gradlew build
    
    - name: Move `.gdap` file to `build/outputs/arr/` folder
      shell: bash
      run: |
        mv ${{ inputs.gdap_file_path }} ${{ inputs.project_path }}/build/outputs/aar/
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{env.OUTPUT_FILENAME}}
        path: ${{ inputs.project_path }}/build/outputs/aar
        retention-days: ${{ inputs.upload_artifact_retention_days }}
